apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dr9z76k2x-go
  janus-idp.io/tekton: dr9z76k2x-go
  backstage.io/kubernetes-id: dr9z76k2x-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dr9z76k2x-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
